version: "3.9"
services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
